### PR TITLE
Fix examples check on CI

### PR DESCRIPTION
**Pull request by jtpio**
Attempt at fixing #31

### CODE REVIEW

**Comment by jtpio** [comment]
Actually the error seems to be related to not finding the `build-labextension` command (which should come from `@jupyterlab/builder`):

```bash
sh: 1: build-labextension: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @jupyterlab/example-federated-middle@2.2.0-alpha.3 build: `npm run clean && build-labextension --core-path ../core_package .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @jupyterlab/example-federated-middle@2.2.0-alpha.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by jtpio** [comment]
However it doesn't seem to be reproducible locally. Running the following commands in a new environment (with node 12) and a fresh copy of the repo builds find:

```bash
jlpm integrity
jlpm run build:packages
jlpm run build:examples
```

**Comment by jtpio** [comment]
Moving the `ensureBuildUtils` step of the integrity steps above seems to fix the examples check: https://github.com/jupyter-rtc/jupyterlab/pull/38/commits/2e1d5cedddfb2c9e8bb0d232cfe6f784bcfe2dd0

CI run: https://github.com/jupyter-rtc/jupyterlab/pull/38/checks?check_run_id=2279958495

The `ensureBuildUtils` function creates the symlinks for the scripts used in `buildutils` and `builder`, including the missing `build-labextension` mentioned aboved:

https://github.com/jupyter-rtc/jupyterlab/blob/877f2c61cad578c49cb96ffb85fd6d31aa603fde/buildutils/src/ensure-repo.ts#L418-L436

So what this means is that with the current structure of the repo, there might a silent error somewhere else in the integrity script that would prevent the the `ensureBuildUtils` step to be run?

**Comment by jtpio** [comment]
@dmonad @hbcarlos @echarles let me know what you think of this diff based on the comments above, which looks like the simplest for now to get the examples check to pass.

The real fix would require checking whether we need to modify anything in the integrity since this repo has the 2 extra packages `docprovider` and `nbmodel`:

https://github.com/jupyter-rtc/jupyterlab/blob/877f2c61cad578c49cb96ffb85fd6d31aa603fde/buildutils/src/ensure-repo.ts#L25-L219

At the moment the examples check passes but still prints this warning:

```
+ jlpm integrity
yarn run v1.21.1
$ node scripts/ensure-buildutils.js && node buildutils/lib/ensure-repo.js
(node:2651) UnhandledPromiseRejectionWarning: Error: Cannot find module 'buffer/package.json'
Require stack:
- /home/runner/work/jupyterlab/jupyterlab/buildutils/lib/utils.js
- /home/runner/work/jupyterlab/jupyterlab/buildutils/lib/ensure-repo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requirePackage (/home/runner/work/jupyterlab/jupyterlab/buildutils/lib/utils.js:305:16)
    at /home/runner/work/jupyterlab/jupyterlab/buildutils/lib/utils.js:281:31
    at Array.forEach (<anonymous>)
    at /home/runner/work/jupyterlab/jupyterlab/buildutils/lib/utils.js:272:27
    at Array.forEach (<anonymous>)
    at Object.getPackageGraph (/home/runner/work/jupyterlab/jupyterlab/buildutils/lib/utils.js:268:25)
(node:2651) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2651) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.61s.
```

And the final `Repo integrity verified!` message is missing.

Happy to open a new issue to track that.

**Comment by echarles** [comment]
We could get that merged with a big comment on in the source linking to this issues, and we can keep that issue open.

Whatever temporary fixes CI is good to have, and we can make sure we revert at some point to have a deeper fix.

**Comment by jtpio** [comment]
Digging a bit more, it looks like `buffer` is coming from one of the new dependencies in the `docprovider` package, which could explain the warning above:

```bash
yarn why v1.21.1
[1/4] Why do we have the module "buffer"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "buffer@5.7.1"
info Has been hoisted to "buffer"
info Reasons this module exists
   - "workspace-aggregator-1d5be243-fcc1-4d74-af18-676704e50b8f" depends on it
   - Hoisted from "_project_#abstract-leveldown#buffer"
   - Hoisted from "_project_#@jupyterlab#docprovider#y-websocket#y-leveldb#level#level-js#buffer"
   - Hoisted from "_project_#@jupyterlab#docprovider#y-websocket#y-leveldb#level#level-packager#encoding-down#abstract-leveldown#buffer"
=> Found "@jupyterlab/apputils#buffer@5.6.0"
info This module exists because "_project_#@jupyterlab#apputils" depends on it.
info Disk size without dependencies: "96KB"
info Disk size with unique dependencies: "132KB"
info Disk size with transitive dependencies: "132KB"
info Number of shared dependencies: 2
=> Found "node-libs-browser#buffer@4.9.2"
info This module exists because "_project_#@jupyterlab#ui-components#@storybook#react#webpack#node-libs-browser" depends on it.
info Disk size without dependencies: "384KB"
info Disk size with unique dependencies: "452KB"
info Disk size with transitive dependencies: "452KB"
info Number of shared dependencies: 3
=> Found "level-codec#buffer@5.6.0"
info This module exists because "_project_#@jupyterlab#docprovider#y-websocket#y-leveldb#level#level-packager#encoding-down#level-codec" depends on it.
Done in 1.78s.

```

**Comment by dmonad** [comment]
docprovider installs `y-websocket`, which installs the `ws` package (an optional dependency), which installs all kinds of node-packages.

**Comment by jtpio** [comment]
Closing as fixed by the latest rebase.

**Pull request closed without merging**
