### PR TITLE
Rebased `rtc` branch

### PR DESCRIPTION
**Pull request by jtpio**
Opening against `master` to check the diff and tests.

### CODE REVIEW

**Comment by dmonad** [comment]
The failing of `js-apputils` is new. The error message complains that the npm package `docprovider` doesn't exist, so it should be fine. Should we rerun the `js-services` tests? It worked before.

**Comment by jtpio** [comment]
Looks like `js-services` also gives the same error:

```
    error Couldn't find package "@jupyterlab/docprovider@^3.1.0-alpha.4" required by "@jupyterlab/docregistry@3.1.0-alpha.4" on the "npm" registry.
```

**Comment by jtpio** [comment]
ah, probably because it is `3.1.0-alpha.3` instead of `3.1.0-alpha.4` (missed during the rebase)

**Comment by jtpio** [comment]
> ah, probably because it is `3.1.0-alpha.3` instead of `3.1.0-alpha.4` (missed during the rebase)

Just forced pushed to fix that.

**Comment by jtpio** [comment]
OK so integrity fails because of another miss during the rebase (alpha 3 -> 4): https://github.com/jupyter-rtc/jupyterlab/pull/50/checks?check_run_id=2343604173

Will force push again to fix.

However it looks like `js-notebook` also fails, but only the test related to undoing changes: https://github.com/jupyter-rtc/jupyterlab/pull/50/checks?check_run_id=2343604760

**Comment by jtpio** [comment]
Closing as fixed by the latest rebase.

**Pull request closed without merging**
