### PR TITLE
Quick pass on the lab code style

### PR DESCRIPTION
**Pull request by jtpio**
## References

Quick pass to do minor edits and comply even more to the JupyterLab TypeScript style guide:

https://github.com/jupyterlab/jupyterlab/wiki/TypeScript-Style-Guide

### TODO

- [ ] Docstrings on all methods
- [x] Check naming of these css classes: 

https://github.com/jupyter-rtc/jupyterlab/blob/877f2c61cad578c49cb96ffb85fd6d31aa603fde/packages/codemirror/style/base.css#L230-L264

## Code changes

Should be about docstrings and naming only.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Marking as ready for review to have this first batch in if it looks good.

**Comment by dmonad** [comment]
We can't rename the css classes that are used for cursors and selections. E.g. `remote-caret` is a css class that is defined by y-codemirror.

Thanks for looking through the code. I agree that it now looks more jupyter-like. Once the tests pass, we can merge this IMO, but let's wait for @echarles approval as well.

**Comment by jtpio** [comment]
> We can't rename the css classes that are used for cursors and selections. E.g. `remote-caret` is a css class that is defined by y-codemirror.

Right, but we can scope them like in https://github.com/jupyter-rtc/jupyterlab/pull/41/commits/481c3493791f5bb5dfcd45eced36159e993f6c11?

**Review by echarles — APPROVED** [review]
LGTM Thx @jtpio As discussed, I will merge this to avoid conflicts on subsequent source changes.

**Comment by dmonad** [comment]
@jtpio Absolutely. I thought you wanted to rename the css classes. Prefixing is fine.

**Review by dmonad — APPROVED** [review]

**Pull request merged**
