### PR TITLE
Skeleton for the shared-model package

### PR DESCRIPTION
**Pull request by echarles**
This is a WIP for discussion to create a new `shared-model` package as discussed with @dmonad .

I will push more and update this note in the coming days.

### CODE REVIEW

**Comment by dmonad** [comment]
Thanks @echarles ! LGTM

**Comment by dmonad** [comment]
Do we align on the `shared-model` naming?

Seeing it alongside the `nbformat` I still think there is some merit in `nbmodel`. 

I like about `shared-model` that it communicates what it does and that it could be a repository for any kind of model that is used in JupyterLab. So we would have a SharedNotebookModel, but also a `SharedFilesystemModel` if we would choose to make the filesystem completely collaborative (just an example).

I'm not sure, however, if it makes sense to implement a local model as well. That would basically just double our work. 

In any case, it would be great if we could merge this PR, so I can start working on it as well. I would start porting the interface that you provided.

**Comment by echarles** [comment]
> Do we align on the shared-model naming?
> Seeing it alongside the nbformat I still think there is some merit in nbmodel.

Naming things is hard but the good thing is that we can change in the short therm. I was getting used to `shared-model` but happy to change to your proposal. JupyterLab is mainly about notebook, but also about file editor and maybe something else in the future, so `nbmodel` sounds a bit too specific to me. We discussed about `model` which is still a good candidate for me. Just tell me before merging what you like, I will change to that.

> I like about shared-model that it communicates what it does and that it could be a repository for any kind of model that is used in JupyterLab. So we would have a SharedNotebookModel, but also a SharedFilesystemModel if we would choose to make the filesystem completely collaborative (just an example).

Makes a lot of sense to me, this is why `model` is maybe something that covers also a shared filesystem.

> I'm not sure, however, if it makes sense to implement a local model as well. That would basically just double our work.

Yes, the `Local`implementation was just something I needed to have a concrete implementation that would compile and apply test on it to have the basic stuff. We can remove it for sure.

> In any case, it would be great if we could merge this PR, so I can start working on it as well. I would start porting the interface that you provided.

Yes, I understand. Would it be possible to give one other day so I can add the signals. For that, we need to discuss how the other packages will use the model, the options are in the spirit of backward compatibly (so having smaller steps for 3.x and the simplifying and breaking for 4.x):

1. `package` uses `shared-model`which uses `observables`- `shared-model` emits lumino signals imported from `observables`.
2.  `package` uses `observable` which uses `shared-model` - `observables` continues to emit lumino signals as it is now.

Do you see other options. What are your thoughts on those? I was planning to try option 1 where this new package would temporary in 3.x depend on `observables` for backwards compatibly reasons. That dependency would be removed in 4.x.

Another thing I'd like to do is already introduce the `@jupyterlab/auth` package that would host the collaborator class (extracted from `observables` - With the model and its signals, and the collaborator,  we could the iterate on the codemirror binding.

These are just thoughts, happy to iterate in other ways.

**Comment by dmonad** [comment]
>  We discussed about model which is still a good candidate for me. Just tell me before merging what you like, I will change to that.

If we would implement a shared-filesystem model, would we create another module or actually implement it in `shared-model`? If we would add all models to `shared-model` then the name is appropriate. Otherwise, we might want to give this model a more specific name. Another advantage of a more specific name would be that we would avoid confusion between `modelDB`, `[
package]/model.s` and `shared-model`. `nbmodel` exactly tells you what you are working with. Either approach makes sense to me. Let's discuss next time we meet.

>Yes, I understand. Would it be possible to give one other day so I can add the signals. For that, we need to discuss how the other packages will use the model, the options are in the spirit of backward compatibly (so having smaller steps for 3.x and the simplifying and breaking for 4.x):
>
> 1. package uses shared-modelwhich uses observables- shared-model emits lumino signals imported from observables.
> 2. package uses observable which uses shared-model - observables continues to emit lumino signals as it is now.

Of course, I can work on Yrs in the meantime. 

I think it would be best if we just implemented `shared-model` without thinking about backwards compatibility. We discussed that it makes sense to use lumino signals in `shared-model`, but we don't necessarily want to keep the old events (only a single change per event). We can polyfill the old event system in the respective `[package]/model.ts` packages. 

Once we got the interface (and a basic implementation) worked out, would you like to pair-program on porting a single package to using `shared-model`. Then we can think about the tradeoffs while talking about something concrete.

**Comment by echarles** [comment]
@dmonad The latest commit take into account our last discussions. Feel free to review and merge.

**Pull request merged**
